"""The migrations match the models, and every one of them can be undone."""

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from dottie.config import settings_without_env_file
from dottie.db import ROOT


@pytest.fixture
def alembic_cfg(database) -> Config:
    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.attributes["settings"] = settings_without_env_file(database_url=database)
    return cfg


def test_models_and_migrations_agree(alembic_cfg):
    try:
        command.check(alembic_cfg)
    except AutogenerateDiffsDetected as e:
        pytest.fail(f'models.py has changes no migration covers; run scripts/db.sh revision "..."\n{e}')


def test_downgrade_to_base_and_back(alembic_cfg):
    command.downgrade(alembic_cfg, "base")
    command.upgrade(alembic_cfg, "head")
