// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BusItem
 */
export type BusItem = {
    message: MessageOut;
    /**
     * Recipient Name
     */
    recipient_name: string;
};

/**
 * ConversationIn
 */
export type ConversationIn = {
    /**
     * Title
     */
    title?: string;
};

/**
 * ConversationOut
 */
export type ConversationOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Dottie Id
     */
    dottie_id: number;
    /**
     * Kind
     */
    kind: string;
    /**
     * Title
     */
    title: string;
    /**
     * Peer Name
     */
    peer_name: string | null;
    /**
     * Preview
     */
    preview: string;
    /**
     * Unread
     */
    unread: number;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DottieIn
 */
export type DottieIn = {
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role?: string;
    /**
     * Personality
     */
    personality?: string;
    /**
     * Hue
     */
    hue?: number;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Tools
     */
    tools?: Array<string>;
    /**
     * Mcp Servers
     */
    mcp_servers?: Array<McpServer>;
    /**
     * Skill Ids
     */
    skill_ids?: Array<number>;
};

/**
 * DottieOut
 */
export type DottieOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Role
     */
    role: string;
    /**
     * Personality
     */
    personality: string;
    /**
     * Hue
     */
    hue: number;
    /**
     * Model
     */
    model: string | null;
    /**
     * Tools
     */
    tools: Array<string>;
    /**
     * Mcp Servers
     */
    mcp_servers: Array<McpServer>;
    /**
     * Skill Ids
     */
    skill_ids: Array<number>;
    /**
     * State
     */
    state: string;
    /**
     * Unread
     */
    unread: number;
    /**
     * Next Run At
     */
    next_run_at: string | null;
    /**
     * Last Woke At
     */
    last_woke_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DottiePatch
 */
export type DottiePatch = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Personality
     */
    personality?: string | null;
    /**
     * Hue
     */
    hue?: number | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Tools
     */
    tools?: Array<string> | null;
    /**
     * Mcp Servers
     */
    mcp_servers?: Array<McpServer> | null;
    /**
     * Skill Ids
     */
    skill_ids?: Array<number> | null;
};

/**
 * EventOut
 */
export type EventOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Dottie Id
     */
    dottie_id: number;
    /**
     * Dottie Name
     */
    dottie_name: string;
    /**
     * Run Id
     */
    run_id: number | null;
    /**
     * Kind
     */
    kind: string;
    /**
     * Text
     */
    text: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InboxItem
 */
export type InboxItem = {
    message: MessageOut;
    /**
     * Dottie Id
     */
    dottie_id: number;
    /**
     * Dottie Name
     */
    dottie_name: string;
    /**
     * Dottie Hue
     */
    dottie_hue: number;
    /**
     * Conversation Title
     */
    conversation_title: string;
};

/**
 * McpServer
 */
export type McpServer = {
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
};

/**
 * MessageIn
 */
export type MessageIn = {
    /**
     * Body
     */
    body: string;
};

/**
 * MessageOut
 */
export type MessageOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Sender Kind
     */
    sender_kind: string;
    /**
     * Sender Id
     */
    sender_id: number | null;
    /**
     * Sender Name
     */
    sender_name: string | null;
    /**
     * Recipient Id
     */
    recipient_id: number | null;
    /**
     * Body
     */
    body: string;
    /**
     * Status
     */
    status: string;
    /**
     * Read At
     */
    read_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PageIn
 */
export type PageIn = {
    /**
     * Content
     */
    content: string;
};

/**
 * PageOut
 */
export type PageOut = {
    /**
     * Path
     */
    path: string;
    /**
     * Size
     */
    size: number;
    /**
     * Updated By
     */
    updated_by: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Content
     */
    content: string;
};

/**
 * PageSummary
 */
export type PageSummary = {
    /**
     * Path
     */
    path: string;
    /**
     * Size
     */
    size: number;
    /**
     * Updated By
     */
    updated_by: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RunOut
 */
export type RunOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Dottie Id
     */
    dottie_id: number;
    /**
     * Conversation Id
     */
    conversation_id: string | null;
    /**
     * Trigger
     */
    trigger: string;
    /**
     * Status
     */
    status: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * ScheduleIn
 */
export type ScheduleIn = {
    /**
     * Title
     */
    title: string;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Cron
     */
    cron?: string | null;
    /**
     * Run At
     */
    run_at?: string | null;
    /**
     * Timezone
     */
    timezone?: string;
};

/**
 * ScheduleOut
 */
export type ScheduleOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Dottie Id
     */
    dottie_id: number;
    /**
     * Dottie Name
     */
    dottie_name: string;
    /**
     * Title
     */
    title: string;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Cron
     */
    cron: string | null;
    /**
     * Run At
     */
    run_at: string | null;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Next Run At
     */
    next_run_at: string | null;
    /**
     * Last Run At
     */
    last_run_at: string | null;
    /**
     * Conversation Id
     */
    conversation_id: string | null;
    /**
     * Created By
     */
    created_by: string;
};

/**
 * SchedulePatch
 */
export type SchedulePatch = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Prompt
     */
    prompt?: string | null;
    /**
     * Cron
     */
    cron?: string | null;
    /**
     * Run At
     */
    run_at?: string | null;
    /**
     * Timezone
     */
    timezone?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
};

/**
 * SkillIn
 */
export type SkillIn = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Body
     */
    body: string;
};

/**
 * SkillOut
 */
export type SkillOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Body
     */
    body: string;
    /**
     * Builtin
     */
    builtin: boolean;
    /**
     * Used By
     */
    used_by: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SkillPatch
 */
export type SkillPatch = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Body
     */
    body?: string | null;
};

/**
 * SystemOut
 */
export type SystemOut = {
    /**
     * Llm Configured
     */
    llm_configured: boolean;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Sandbox Backend
     */
    sandbox_backend: string;
    /**
     * Engine Running
     */
    engine_running: boolean;
    /**
     * Timezone
     */
    timezone: string;
};

/**
 * TemplateOut
 */
export type TemplateOut = {
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: string;
    /**
     * Hue
     */
    hue: number;
    /**
     * Personality
     */
    personality: string;
    /**
     * Tools
     */
    tools: Array<string>;
    /**
     * Skills
     */
    skills: Array<string>;
};

/**
 * ToolkitOut
 */
export type ToolkitOut = {
    /**
     * Key
     */
    key: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Response Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ListToolkitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/toolkits';
};

export type ListToolkitsResponses = {
    /**
     * Response List Toolkits
     *
     * Successful Response
     */
    200: Array<ToolkitOut>;
};

export type ListToolkitsResponse = ListToolkitsResponses[keyof ListToolkitsResponses];

export type ListTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/templates';
};

export type ListTemplatesResponses = {
    /**
     * Response List Templates
     *
     * Successful Response
     */
    200: Array<TemplateOut>;
};

export type ListTemplatesResponse = ListTemplatesResponses[keyof ListTemplatesResponses];

export type ListDottiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dotties';
};

export type ListDottiesResponses = {
    /**
     * Response List Dotties
     *
     * Successful Response
     */
    200: Array<DottieOut>;
};

export type ListDottiesResponse = ListDottiesResponses[keyof ListDottiesResponses];

export type CreateDottieData = {
    body: DottieIn;
    path?: never;
    query?: never;
    url: '/api/dotties';
};

export type CreateDottieErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDottieError = CreateDottieErrors[keyof CreateDottieErrors];

export type CreateDottieResponses = {
    /**
     * Successful Response
     */
    201: DottieOut;
};

export type CreateDottieResponse = CreateDottieResponses[keyof CreateDottieResponses];

export type DeleteDottieData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}';
};

export type DeleteDottieErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDottieError = DeleteDottieErrors[keyof DeleteDottieErrors];

export type DeleteDottieResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDottieResponse = DeleteDottieResponses[keyof DeleteDottieResponses];

export type GetDottieData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}';
};

export type GetDottieErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDottieError = GetDottieErrors[keyof GetDottieErrors];

export type GetDottieResponses = {
    /**
     * Successful Response
     */
    200: DottieOut;
};

export type GetDottieResponse = GetDottieResponses[keyof GetDottieResponses];

export type UpdateDottieData = {
    body: DottiePatch;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}';
};

export type UpdateDottieErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDottieError = UpdateDottieErrors[keyof UpdateDottieErrors];

export type UpdateDottieResponses = {
    /**
     * Successful Response
     */
    200: DottieOut;
};

export type UpdateDottieResponse = UpdateDottieResponses[keyof UpdateDottieResponses];

export type ListConversationsData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}/conversations';
};

export type ListConversationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConversationsError = ListConversationsErrors[keyof ListConversationsErrors];

export type ListConversationsResponses = {
    /**
     * Response List Conversations
     *
     * Successful Response
     */
    200: Array<ConversationOut>;
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type CreateConversationData = {
    body: ConversationIn;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}/conversations';
};

export type CreateConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationError = CreateConversationErrors[keyof CreateConversationErrors];

export type CreateConversationResponses = {
    /**
     * Successful Response
     */
    201: ConversationOut;
};

export type CreateConversationResponse = CreateConversationResponses[keyof CreateConversationResponses];

export type DeleteConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}';
};

export type DeleteConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationError = DeleteConversationErrors[keyof DeleteConversationErrors];

export type DeleteConversationResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConversationResponse = DeleteConversationResponses[keyof DeleteConversationResponses];

export type ListMessagesData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: {
        /**
         * After
         */
        after?: number;
    };
    url: '/api/conversations/{conversation_id}/messages';
};

export type ListMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesError = ListMessagesErrors[keyof ListMessagesErrors];

export type ListMessagesResponses = {
    /**
     * Response List Messages
     *
     * Successful Response
     */
    200: Array<MessageOut>;
};

export type ListMessagesResponse = ListMessagesResponses[keyof ListMessagesResponses];

export type SendMessageData = {
    body: MessageIn;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/messages';
};

export type SendMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors];

export type SendMessageResponses = {
    /**
     * Successful Response
     */
    201: MessageOut;
};

export type SendMessageResponse = SendMessageResponses[keyof SendMessageResponses];

export type MarkReadData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/read';
};

export type MarkReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkReadError = MarkReadErrors[keyof MarkReadErrors];

export type MarkReadResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MarkReadResponse = MarkReadResponses[keyof MarkReadResponses];

export type InboxData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/inbox';
};

export type InboxErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InboxError = InboxErrors[keyof InboxErrors];

export type InboxResponses = {
    /**
     * Response Inbox
     *
     * Successful Response
     */
    200: Array<InboxItem>;
};

export type InboxResponse = InboxResponses[keyof InboxResponses];

export type ReadInboxData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inbox/read';
};

export type ReadInboxResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ReadInboxResponse = ReadInboxResponses[keyof ReadInboxResponses];

export type TrafficData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/bus';
};

export type TrafficErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TrafficError = TrafficErrors[keyof TrafficErrors];

export type TrafficResponses = {
    /**
     * Response Traffic
     *
     * Successful Response
     */
    200: Array<BusItem>;
};

export type TrafficResponse = TrafficResponses[keyof TrafficResponses];

export type ListPagesData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}/wiki';
};

export type ListPagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPagesError = ListPagesErrors[keyof ListPagesErrors];

export type ListPagesResponses = {
    /**
     * Response List Pages
     *
     * Successful Response
     */
    200: Array<PageSummary>;
};

export type ListPagesResponse = ListPagesResponses[keyof ListPagesResponses];

export type DeletePageData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}/wiki/{path}';
};

export type DeletePageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePageError = DeletePageErrors[keyof DeletePageErrors];

export type DeletePageResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePageResponse = DeletePageResponses[keyof DeletePageResponses];

export type ReadPageData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}/wiki/{path}';
};

export type ReadPageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPageError = ReadPageErrors[keyof ReadPageErrors];

export type ReadPageResponses = {
    /**
     * Successful Response
     */
    200: PageOut;
};

export type ReadPageResponse = ReadPageResponses[keyof ReadPageResponses];

export type WritePageData = {
    body: PageIn;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}/wiki/{path}';
};

export type WritePageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WritePageError = WritePageErrors[keyof WritePageErrors];

export type WritePageResponses = {
    /**
     * Successful Response
     */
    200: PageOut;
};

export type WritePageResponse = WritePageResponses[keyof WritePageResponses];

export type ListAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/schedules';
};

export type ListAllResponses = {
    /**
     * Response List All
     *
     * Successful Response
     */
    200: Array<ScheduleOut>;
};

export type ListAllResponse = ListAllResponses[keyof ListAllResponses];

export type ListSchedulesData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}/schedules';
};

export type ListSchedulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSchedulesError = ListSchedulesErrors[keyof ListSchedulesErrors];

export type ListSchedulesResponses = {
    /**
     * Response List Schedules
     *
     * Successful Response
     */
    200: Array<ScheduleOut>;
};

export type ListSchedulesResponse = ListSchedulesResponses[keyof ListSchedulesResponses];

export type CreateScheduleData = {
    body: ScheduleIn;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: never;
    url: '/api/dotties/{dottie_id}/schedules';
};

export type CreateScheduleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScheduleError = CreateScheduleErrors[keyof CreateScheduleErrors];

export type CreateScheduleResponses = {
    /**
     * Successful Response
     */
    201: ScheduleOut;
};

export type CreateScheduleResponse = CreateScheduleResponses[keyof CreateScheduleResponses];

export type DeleteScheduleData = {
    body?: never;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: number;
    };
    query?: never;
    url: '/api/schedules/{schedule_id}';
};

export type DeleteScheduleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScheduleError = DeleteScheduleErrors[keyof DeleteScheduleErrors];

export type DeleteScheduleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteScheduleResponse = DeleteScheduleResponses[keyof DeleteScheduleResponses];

export type UpdateScheduleData = {
    body: SchedulePatch;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: number;
    };
    query?: never;
    url: '/api/schedules/{schedule_id}';
};

export type UpdateScheduleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateScheduleError = UpdateScheduleErrors[keyof UpdateScheduleErrors];

export type UpdateScheduleResponses = {
    /**
     * Successful Response
     */
    200: ScheduleOut;
};

export type UpdateScheduleResponse = UpdateScheduleResponses[keyof UpdateScheduleResponses];

export type RunNowData = {
    body?: never;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: number;
    };
    query?: never;
    url: '/api/schedules/{schedule_id}/run';
};

export type RunNowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunNowError = RunNowErrors[keyof RunNowErrors];

export type RunNowResponses = {
    /**
     * Successful Response
     */
    202: ScheduleOut;
};

export type RunNowResponse = RunNowResponses[keyof RunNowResponses];

export type ListSkillsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/skills';
};

export type ListSkillsResponses = {
    /**
     * Response List Skills
     *
     * Successful Response
     */
    200: Array<SkillOut>;
};

export type ListSkillsResponse = ListSkillsResponses[keyof ListSkillsResponses];

export type CreateSkillData = {
    body: SkillIn;
    path?: never;
    query?: never;
    url: '/api/skills';
};

export type CreateSkillErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSkillError = CreateSkillErrors[keyof CreateSkillErrors];

export type CreateSkillResponses = {
    /**
     * Successful Response
     */
    201: SkillOut;
};

export type CreateSkillResponse = CreateSkillResponses[keyof CreateSkillResponses];

export type DeleteSkillData = {
    body?: never;
    path: {
        /**
         * Skill Id
         */
        skill_id: number;
    };
    query?: never;
    url: '/api/skills/{skill_id}';
};

export type DeleteSkillErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSkillError = DeleteSkillErrors[keyof DeleteSkillErrors];

export type DeleteSkillResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSkillResponse = DeleteSkillResponses[keyof DeleteSkillResponses];

export type UpdateSkillData = {
    body: SkillPatch;
    path: {
        /**
         * Skill Id
         */
        skill_id: number;
    };
    query?: never;
    url: '/api/skills/{skill_id}';
};

export type UpdateSkillErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSkillError = UpdateSkillErrors[keyof UpdateSkillErrors];

export type UpdateSkillResponses = {
    /**
     * Successful Response
     */
    200: SkillOut;
};

export type UpdateSkillResponse = UpdateSkillResponses[keyof UpdateSkillResponses];

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Before
         */
        before?: number | null;
    };
    url: '/api/events';
};

export type ListEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsError = ListEventsErrors[keyof ListEventsErrors];

export type ListEventsResponses = {
    /**
     * Response List Events
     *
     * Successful Response
     */
    200: Array<EventOut>;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type ListDottieEventsData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Before
         */
        before?: number | null;
    };
    url: '/api/dotties/{dottie_id}/events';
};

export type ListDottieEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDottieEventsError = ListDottieEventsErrors[keyof ListDottieEventsErrors];

export type ListDottieEventsResponses = {
    /**
     * Response List Dottie Events
     *
     * Successful Response
     */
    200: Array<EventOut>;
};

export type ListDottieEventsResponse = ListDottieEventsResponses[keyof ListDottieEventsResponses];

export type ListRunsData = {
    body?: never;
    path: {
        /**
         * Dottie Id
         */
        dottie_id: number;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/dotties/{dottie_id}/runs';
};

export type ListRunsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRunsError = ListRunsErrors[keyof ListRunsErrors];

export type ListRunsResponses = {
    /**
     * Response List Runs
     *
     * Successful Response
     */
    200: Array<RunOut>;
};

export type ListRunsResponse = ListRunsResponses[keyof ListRunsResponses];

export type SystemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system';
};

export type SystemResponses = {
    /**
     * Successful Response
     */
    200: SystemOut;
};

export type SystemResponse = SystemResponses[keyof SystemResponses];

export type StreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/stream';
};

export type StreamResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
