"""owners

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-07 17:38:36.089955
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dotties", sa.Column("owner_id", sa.String(length=64), server_default="local", nullable=False))
    op.create_index(op.f("ix_dotties_owner_id"), "dotties", ["owner_id"], unique=False)
    op.add_column("skills", sa.Column("owner_id", sa.String(length=64), server_default="", nullable=False))
    # what existed before there were users belongs to the one local user; built-in skills stay everyone's ("")
    op.execute("UPDATE skills SET owner_id = 'local' WHERE NOT builtin")
    op.drop_constraint(op.f("uq_skills_name"), "skills", type_="unique")
    op.create_unique_constraint(op.f("uq_skills_owner_id"), "skills", ["owner_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_skills_owner_id"), "skills", type_="unique")
    op.create_unique_constraint(op.f("uq_skills_name"), "skills", ["name"], postgresql_nulls_not_distinct=False)
    op.drop_column("skills", "owner_id")
    op.drop_index(op.f("ix_dotties_owner_id"), table_name="dotties")
    op.drop_column("dotties", "owner_id")
    # ### end Alembic commands ###
