"""run token and message run

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 16:07:25.145342
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("run_id", sa.Integer(), nullable=True))
    op.create_foreign_key(op.f("fk_messages_run_id_runs"), "messages", "runs", ["run_id"], ["id"], ondelete="SET NULL")
    op.add_column("runs", sa.Column("token", sa.String(length=64), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "token")
    op.drop_constraint(op.f("fk_messages_run_id_runs"), "messages", type_="foreignkey")
    op.drop_column("messages", "run_id")
    # ### end Alembic commands ###
