"""sandbox awake

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 17:09:19.145134
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dotties", sa.Column("sandbox_awake", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dotties", "sandbox_awake")
    # ### end Alembic commands ###
