from datetime import datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    # named constraints: autogenerated migrations can then alter and drop them by name
    metadata = MetaData(
        naming_convention={
            "ix": "ix_%(column_0_label)s",
            "uq": "uq_%(table_name)s_%(column_0_name)s",
            "ck": "ck_%(table_name)s_%(constraint_name)s",
            "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
            "pk": "pk_%(table_name)s",
        }
    )


def _now() -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), server_default=func.now())


class Skill(Base):
    """A reusable procedure (a SKILL.md) any dottie can be given: one shared library, assigned per dottie."""

    __tablename__ = "skills"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(64), unique=True)  # lowercase-hyphen: it is the skill's directory name
    description: Mapped[str] = mapped_column(String(1024))  # when to use it: the only part always in the prompt
    body: Mapped[str] = mapped_column(Text)
    builtin: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = _now()


class DottieSkill(Base):
    __tablename__ = "dottie_skills"

    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), primary_key=True)
    skill_id: Mapped[int] = mapped_column(ForeignKey("skills.id", ondelete="CASCADE"), primary_key=True)


class Dottie(Base):
    """A persistent agent. Everything that makes it itself is in the database; its sandbox is only its computer."""

    __tablename__ = "dotties"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(80))
    slug: Mapped[str] = mapped_column(String(80), unique=True)  # how other dotties address it
    role: Mapped[str] = mapped_column(String(200), default="")  # one line: what it is for
    personality: Mapped[str] = mapped_column(Text, default="")  # the system prompt's character part
    hue: Mapped[int] = mapped_column(Integer, default=250)  # its colour (0-360): avatar and accents
    model: Mapped[str | None] = mapped_column(String(120), default=None)  # overrides the default deployment
    tools: Mapped[list[str]] = mapped_column(JSONB, default=list)  # enabled toolkits: see engine/tools.py
    mcp_servers: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, default=list)  # [{"name", "url"}]
    sandbox_ref: Mapped[str | None] = mapped_column(String(200), default=None)  # its computer, once it has one
    last_woke_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    created_at: Mapped[datetime] = _now()

    skills: Mapped[list[Skill]] = relationship(secondary="dottie_skills", order_by=Skill.name)


class WikiPage(Base):
    """A page of a dottie's long-term knowledge: markdown files at paths, like an LLM wiki (index.md, log.md, ...)."""

    __tablename__ = "wiki_pages"
    __table_args__ = (UniqueConstraint("dottie_id", "path"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"))
    path: Mapped[str] = mapped_column(String(300))  # "index.md", "people/anna.md": no leading slash
    content: Mapped[str] = mapped_column(Text, default="")
    updated_by: Mapped[str] = mapped_column(String(20), default="dottie")  # dottie | user
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Conversation(Base):
    """A thread: one LangGraph thread and one chat window. `peer` is the other dottie in a dottie-to-dottie thread."""

    __tablename__ = "conversations"

    id: Mapped[str] = mapped_column(String(40), primary_key=True)  # also the LangGraph thread id
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), index=True)
    kind: Mapped[str] = mapped_column(String(10))  # chat | schedule | dottie
    title: Mapped[str] = mapped_column(String(200), default="")
    peer_id: Mapped[int | None] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), default=None)
    created_at: Mapped[datetime] = _now()
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Message(Base):
    """The messaging layer: a durable inbox. A `pending` message to a dottie is what wakes it."""

    __tablename__ = "messages"
    __table_args__ = (Index("ix_messages_status_recipient", "status", "recipient_id"),)

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    conversation_id: Mapped[str] = mapped_column(ForeignKey("conversations.id", ondelete="CASCADE"), index=True)
    sender_kind: Mapped[str] = mapped_column(String(10))  # user | dottie | scheduler
    sender_id: Mapped[int | None] = mapped_column(ForeignKey("dotties.id", ondelete="SET NULL"), default=None)
    recipient_id: Mapped[int | None] = mapped_column(  # None: addressed to the user
        ForeignKey("dotties.id", ondelete="CASCADE"), default=None
    )
    body: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(12), default="pending")  # pending | processing | done | failed
    depth: Mapped[int] = mapped_column(Integer, default=0)  # hops since a human or the clock: stops message loops
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)  # for the user's inbox
    created_at: Mapped[datetime] = _now()


class Schedule(Base):
    """Something to do later or repeatedly. The scheduler turns each firing into a message that wakes the dottie."""

    __tablename__ = "schedules"
    __table_args__ = (Index("ix_schedules_due", "enabled", "next_run_at"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), index=True)
    title: Mapped[str] = mapped_column(String(200))
    prompt: Mapped[str] = mapped_column(Text)
    cron: Mapped[str | None] = mapped_column(String(100), default=None)  # recurring, or...
    run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)  # ...once
    timezone: Mapped[str] = mapped_column(String(60), default="UTC")
    enabled: Mapped[bool] = mapped_column(Boolean, default=True)
    next_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    last_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    conversation_id: Mapped[str | None] = mapped_column(
        String(40), default=None
    )  # its thread, so runs build on each other
    created_by: Mapped[str] = mapped_column(String(10), default="user")  # user | dottie
    created_at: Mapped[datetime] = _now()


class Run(Base):
    """One waking: what woke the dottie, how it went. Rows still `running` after a restart are failed at startup."""

    __tablename__ = "runs"

    id: Mapped[int] = mapped_column(primary_key=True)
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), index=True)
    conversation_id: Mapped[str | None] = mapped_column(ForeignKey("conversations.id", ondelete="SET NULL"))
    trigger: Mapped[str] = mapped_column(String(10))  # user | scheduler | dottie
    status: Mapped[str] = mapped_column(String(10), default="running")  # running | done | failed
    summary: Mapped[str] = mapped_column(Text, default="")
    started_at: Mapped[datetime] = _now()
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)


class Event(Base):
    """The activity feed: what a dottie did while awake (wake, tool calls, messages sent, wiki edits, sleep)."""

    __tablename__ = "events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), index=True)
    run_id: Mapped[int | None] = mapped_column(ForeignKey("runs.id", ondelete="CASCADE"), index=True, default=None)
    kind: Mapped[str] = mapped_column(String(20))  # wake | tool | tool_result | sent | wiki | sleep | error
    text: Mapped[str] = mapped_column(Text, default="")
    data: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict)
    created_at: Mapped[datetime] = _now()
