from datetime import datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    # named constraints: autogenerated migrations can then alter and drop them by name
    metadata = MetaData(
        naming_convention={
            "ix": "ix_%(column_0_label)s",
            "uq": "uq_%(table_name)s_%(column_0_name)s",
            "ck": "ck_%(table_name)s_%(constraint_name)s",
            "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
            "pk": "pk_%(table_name)s",
        }
    )


def _now() -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), server_default=func.now())


class Skill(Base):
    """A reusable procedure (a SKILL.md) any dottie can be given: one shared library, assigned per dottie."""

    __tablename__ = "skills"
    __table_args__ = (UniqueConstraint("owner_id", "name"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    owner_id: Mapped[str] = mapped_column(String(64), default="", server_default="")  # "": built in, for everyone
    name: Mapped[str] = mapped_column(
        String(64)
    )  # lowercase-hyphen: it is the skill's directory name, unique per owner
    description: Mapped[str] = mapped_column(String(1024))  # when to use it: the only part always in the prompt
    body: Mapped[str] = mapped_column(Text)
    builtin: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = _now()


class DottieSkill(Base):
    __tablename__ = "dottie_skills"

    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), primary_key=True)
    skill_id: Mapped[int] = mapped_column(ForeignKey("skills.id", ondelete="CASCADE"), primary_key=True)


class Dottie(Base):
    """A persistent agent. Everything that makes it itself is in the database; its sandbox is only its computer."""

    __tablename__ = "dotties"

    id: Mapped[int] = mapped_column(primary_key=True)
    owner_id: Mapped[str] = mapped_column(String(64), index=True, default="local", server_default="local")  # the user
    name: Mapped[str] = mapped_column(String(80))
    slug: Mapped[str] = mapped_column(String(80), unique=True)  # how other dotties address it
    role: Mapped[str] = mapped_column(String(200), default="")  # one line: what it is for
    personality: Mapped[str] = mapped_column(Text, default="")  # the system prompt's character part
    hue: Mapped[int] = mapped_column(Integer, default=250)  # its colour (0-360): avatar and accents
    model: Mapped[str | None] = mapped_column(String(120), default=None)  # overrides the default deployment
    tools: Mapped[list[str]] = mapped_column(JSONB, default=list)  # enabled toolkits: see engine/tools.py
    mcp_servers: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, default=list)  # [{"name", "url"}]
    sandbox_ref: Mapped[str | None] = mapped_column(String(200), default=None)  # its computer, once it has one
    sandbox_awake: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")  # that computer runs
    last_woke_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    created_at: Mapped[datetime] = _now()

    skills: Mapped[list[Skill]] = relationship(secondary="dottie_skills", order_by=Skill.name)


class Secret(Base):
    """A value a user keeps for their dotties (an API key for an MCP server). Write-only: only the app reads it back,
    to fill it into a connection; the API only ever shows its name and a hint."""

    __tablename__ = "secrets"
    __table_args__ = (UniqueConstraint("owner_id", "name"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    owner_id: Mapped[str] = mapped_column(String(64), index=True)
    name: Mapped[str] = mapped_column(String(40))
    ciphertext: Mapped[str] = mapped_column(Text)
    hint: Mapped[str] = mapped_column(String(8), default="")  # the last characters, to tell two keys apart
    created_at: Mapped[datetime] = _now()
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class ApiToken(Base):
    """A personal access token: lets a user's other tools (an MCP client) act as them. Only its hash is kept."""

    __tablename__ = "api_tokens"

    id: Mapped[int] = mapped_column(primary_key=True)
    owner_id: Mapped[str] = mapped_column(String(64), index=True)
    name: Mapped[str] = mapped_column(String(80))
    token_hash: Mapped[str] = mapped_column(String(64), unique=True)  # sha256 of the token
    created_at: Mapped[datetime] = _now()
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)


class WikiPage(Base):
    """A page of a dottie's long-term knowledge: markdown files at paths, like an LLM wiki (index.md, log.md, ...)."""

    __tablename__ = "wiki_pages"
    __table_args__ = (UniqueConstraint("dottie_id", "path"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"))
    path: Mapped[str] = mapped_column(String(300))  # "index.md", "people/anna.md": no leading slash
    content: Mapped[str] = mapped_column(Text, default="")
    updated_by: Mapped[str] = mapped_column(String(20), default="dottie")  # dottie | user
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Conversation(Base):
    """A thread: one LangGraph thread and one chat window. `peer` is the other dottie in a dottie-to-dottie thread."""

    __tablename__ = "conversations"

    id: Mapped[str] = mapped_column(String(40), primary_key=True)  # also the LangGraph thread id
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), index=True)
    kind: Mapped[str] = mapped_column(String(10))  # chat | schedule | dottie
    title: Mapped[str] = mapped_column(String(200), default="")
    peer_id: Mapped[int | None] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), default=None)
    # dottie threads: the conversation with the user that last asked this dottie to delegate, where answers go back to
    origin_id: Mapped[str | None] = mapped_column(ForeignKey("conversations.id", ondelete="SET NULL"), default=None)
    created_at: Mapped[datetime] = _now()
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Message(Base):
    """The messaging layer: a durable inbox. A `pending` message to a dottie is what wakes it."""

    __tablename__ = "messages"
    __table_args__ = (Index("ix_messages_status_recipient", "status", "recipient_id"),)

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    conversation_id: Mapped[str] = mapped_column(ForeignKey("conversations.id", ondelete="CASCADE"), index=True)
    sender_kind: Mapped[str] = mapped_column(String(10))  # user | dottie | scheduler
    sender_id: Mapped[int | None] = mapped_column(ForeignKey("dotties.id", ondelete="SET NULL"), default=None)
    recipient_id: Mapped[int | None] = mapped_column(  # None: addressed to the user
        ForeignKey("dotties.id", ondelete="CASCADE"), default=None
    )
    body: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(12), default="pending")  # pending | processing | done | failed
    depth: Mapped[int] = mapped_column(Integer, default=0)  # hops since a human or the clock: stops message loops
    run_id: Mapped[int | None] = mapped_column(ForeignKey("runs.id", ondelete="SET NULL"), default=None)  # handled in
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)  # for the user's inbox
    created_at: Mapped[datetime] = _now()


class TelegramLink(Base):
    """A Telegram chat that talks to a user's dotties. It starts as a pending code (made in the app, sent to the bot as
    `/start <code>`), which is what proves the chat belongs to that user. `conversation_id` is where the chat's messages
    go: the one with the dottie the user picked. `sent_up_to` is the last message id already delivered to the chat."""

    __tablename__ = "telegram_links"

    id: Mapped[int] = mapped_column(primary_key=True)
    owner_id: Mapped[str] = mapped_column(String(64), index=True)
    code: Mapped[str | None] = mapped_column(String(40), unique=True, default=None)  # until the chat has used it
    chat_id: Mapped[int | None] = mapped_column(BigInteger, unique=True, default=None)
    dottie_id: Mapped[int | None] = mapped_column(ForeignKey("dotties.id", ondelete="SET NULL"), default=None)
    conversation_id: Mapped[str | None] = mapped_column(
        ForeignKey("conversations.id", ondelete="SET NULL"), default=None
    )
    sent_up_to: Mapped[int] = mapped_column(BigInteger, default=0, server_default="0")
    created_at: Mapped[datetime] = _now()


class Schedule(Base):
    """Something to do later or repeatedly. The scheduler turns each firing into a message that wakes the dottie."""

    __tablename__ = "schedules"
    __table_args__ = (Index("ix_schedules_due", "enabled", "next_run_at"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), index=True)
    title: Mapped[str] = mapped_column(String(200))
    prompt: Mapped[str] = mapped_column(Text)
    cron: Mapped[str | None] = mapped_column(String(100), default=None)  # recurring, or...
    run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)  # ...once
    timezone: Mapped[str] = mapped_column(String(60), default="UTC")
    enabled: Mapped[bool] = mapped_column(Boolean, default=True)
    next_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    last_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    conversation_id: Mapped[str | None] = mapped_column(
        String(40), default=None
    )  # its thread, so runs build on each other
    created_by: Mapped[str] = mapped_column(String(10), default="user")  # user | dottie
    created_at: Mapped[datetime] = _now()


class Run(Base):
    """One waking: what woke the dottie, how it went. Rows still `running` after a restart are failed at startup."""

    __tablename__ = "runs"

    id: Mapped[int] = mapped_column(primary_key=True)
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), index=True)
    conversation_id: Mapped[str | None] = mapped_column(ForeignKey("conversations.id", ondelete="SET NULL"))
    trigger: Mapped[str] = mapped_column(String(10))  # user | scheduler | dottie
    status: Mapped[str] = mapped_column(String(10), default="running")  # running | done | failed
    summary: Mapped[str] = mapped_column(Text, default="")
    token: Mapped[str] = mapped_column(
        String(64), default="", server_default=""
    )  # what the agent in the sandbox calls back with
    started_at: Mapped[datetime] = _now()
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)


class Event(Base):
    """The activity feed: what a dottie did while awake (wake, tool calls, messages sent, wiki edits, sleep)."""

    __tablename__ = "events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    dottie_id: Mapped[int] = mapped_column(ForeignKey("dotties.id", ondelete="CASCADE"), index=True)
    run_id: Mapped[int | None] = mapped_column(ForeignKey("runs.id", ondelete="CASCADE"), index=True, default=None)
    kind: Mapped[str] = mapped_column(String(20))  # wake | tool | tool_result | sent | wiki | sleep | error
    text: Mapped[str] = mapped_column(Text, default="")
    data: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict)
    created_at: Mapped[datetime] = _now()
