#!/usr/bin/env bash
# The local PostgreSQL (compose.yaml) and its migrations.
#   scripts/db.sh up                  # start it (port 54845) and wait until it answers
#   scripts/db.sh down                # stop it; the data stays in the volume
#   scripts/db.sh reset               # stop it and delete the data (app and test databases)
#   scripts/db.sh psql [db]           # a psql shell (dottie, or e.g. dottie_test)
#   scripts/db.sh migrate             # upgrade to the latest migration (the app also does this at startup)
#   scripts/db.sh revision "message"  # a new migration, autogenerated from models.py: read it, then migrate
#   scripts/db.sh downgrade [rev]     # one step back (or to rev)
set -euo pipefail
cd "$(dirname "$0")/.."
# shellcheck source=scripts/lib.sh
source scripts/lib.sh

need docker "https://docs.docker.com/get-docker/"
compose() { docker compose "$@"; }

case "${1:-}" in
  up)
    compose up -d --wait --quiet-pull db >/dev/null 2>&1 || {
      compose logs --tail 30 db >&2
      echo "PostgreSQL did not start (logs above)." >&2
      exit 1
    }
    echo "PostgreSQL is up on 127.0.0.1:54845"
    ;;
  down) compose down ;;
  reset)
    confirm "Delete the local database and all its data?"
    compose down -v
    ;;
  psql) compose exec db psql -U dottie "${2:-dottie}" ;;
  migrate) uv run alembic upgrade head ;;
  revision)
    [ -n "${2:-}" ] || { echo "usage: $0 revision \"what changes\"" >&2; exit 1; }
    uv run alembic upgrade head  # autogenerate compares against the database: bring it up to date first
    uv run alembic revision --autogenerate -m "$2"
    echo "Read the new file in migrations/versions/ before applying it (renames come out as drop + add)."
    ;;
  downgrade) uv run alembic downgrade "${2:--1}" ;;
  *)
    sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'
    exit 1
    ;;
esac
